baseURL: https://konumaru.org/
title: konumaru blog
paginate: 10
theme: PaperMod

timeZone: "Asia/Tokyo"
languageCode: en
DefaultContentLanguage: en
HasCJKLanguage: true
enableRobotsTXT: true
enableEmoji: true

enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: "G-YKYR14NJJ2"

permalinks:
  posts: "/:year:month/:filename/"

menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
    - name: Search
      url: search/
      weight: 6
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 5

taxonomies:
  category: categories
  tag: tags

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  defaultTheme: auto # auto, dark
  ShowToc: true
  tocopen: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  disableAnchoredHeadings: false

  homeInfoParams:
    Title: konumaru blog
    Content: >
      - Welcome to konumaru blog. I write down what I learned recently and what I think about works or something.

      - My Media Art works are also posted [here](https://konumaru.org/p5gallery/).

  socialIcons:
    - name: rss
      url: "index.xml"
    - name: x
      url: "https://x.com/konumaruuu_v2"
    - name: github
      url: "https://github.com/konumaru"
    - name: kaggle
      url: "https://www.kaggle.com/konumaru"
    - name: spotify
      url: "https://open.spotify.com/user/q32d9akx5hh3lqnga5jd1xfst"
    - name: buymeacoffee
      url: https://www.buymeacoffee.com/konumaru10C


  editPost:
    URL: "https://github.com/konumaru/konumaru.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true # to append file path to Edit link

  # For search
  fuseOpts:
    # ref: https://fusejs.io/api/options.html
    threshold: 0.4
  
# favicon
# generated by https://favicon.io/
assets:
  favicon: "/favicon.ico"
  favicon16x16: "/favicon16x16.png"
  favicon32x32: "/favicon32x32.png"
  apple_touch_icon: "/apple-touch-icon.png"

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
