# 公開するページのURL
baseURL = "https://kat0h.github.io/hugo-blog-template"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "hugo-blog-template"

theme = "PaperMod"
paginate = 20
