# 公開するページのURL
baseURL = "https://konumaru.github.io/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "konumaru blog"

theme = "PaperMod"
paginate = 20
