baseURL: "https://konumaru.github.io/"
title: konumaru blog
theme: PaperMod
paginate: 20
languageCode: en
DefaultContentLanguage: en
HasCJKLanguage: true
enableRobotsTXT: true
enableEmoji: true
menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Search
      url: search/
      weight: 10
params:
  homeInfoParams:
    Title: Hi there wave
    Content: Welcome to my blog
  socialIcons:
    - name: twitter
      url: "https://twitter.com/knmr_u"
    - name: github
      url: "https://github.com/konumaru"
    - name: RsS
      url: "index.xml"
  fuseOpts:
    # ref: https://fusejs.io/api/options.html
    threshold: 0.4
  ShowToc: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  editPost:
    URL: "https://github.com/konumaru/konumaru.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
outputs:
  home:
    - HTML
    - RSS
    - JSON
