baseURL: "https://konumaru.github.io/"
title: konumaru blog
theme: PaperMod
paginate: 10

languageCode: en
DefaultContentLanguage: en
HasCJKLanguage: true
enableRobotsTXT: true
enableEmoji: true

permalinks:
  posts: "/:year/:month:/:title/"

menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: Search
      url: search/
      weight: 10

params:
  defaultTheme: dark # auto
  ShowToc: true
  tocopen: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: konumaru blog
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/knmr_u"
    - name: github
      url: "https://github.com/konumaru"
    - name: rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/konumaru/konumaru.github.io/tree/main/content"
    Text: "Edit"
    appendFilePath: true # to append file path to Edit link

  # For search
  fuseOpts:
    # ref: https://fusejs.io/api/options.html
    threshold: 0.4

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  amazonJpAffiliate: "konumaru-22"

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
