name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch to deploy
    paths-ignore:
      - "**/README.md"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone PaperMod Theme
        run: |
          # Remove themes/PaperMod if exists
          rm -rf themes/PaperMod
          # Clone PaperMod theme directly
          git clone --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
          # Verify theme was cloned successfully
          ls -la themes/PaperMod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.147.1"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
